{"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration\/TSIdo"],"title":"Classes"},{"identifiers":["doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration\/TSIdoClientResponseOption","doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration\/TSIdoDelegate","doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration\/TSIdoServiceResponse"],"title":"Protocols"},{"identifiers":["doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration\/TSIdoInitJourneyOptions","doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration\/TSIdoSdkError","doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration\/TSIdoStartJourneyOptions"],"title":"Structures"},{"identifiers":["doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration\/TSIdoGenerateDebugPinCompletion"],"title":"Type Aliases"},{"title":"Enumerations","identifiers":["doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration\/TSIdoClientResponseOptionType","doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration\/TSIdoJourneyActionType","doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration\/TSIdoJourneyError"]},{"identifiers":["doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration\/Swift"],"title":"Extended Modules"}],"hierarchy":{"paths":[[]]},"identifier":{"url":"doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"externalID":"IdentityOrchestration","symbolKind":"module","role":"collection","modules":[{"name":"IdentityOrchestration"}],"title":"IdentityOrchestration","roleHeading":"Framework"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/identityorchestration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/identityorchestration"]}],"references":{"doc://com.TransmitSecurity.IdentityOrchestration/documentation/IdentityOrchestration/TSIdo":{"abstract":[],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TSIdo"}],"identifier":"doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration\/TSIdo","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSIdo"}],"title":"TSIdo","url":"\/documentation\/identityorchestration\/tsido"},"doc://com.TransmitSecurity.IdentityOrchestration/documentation/IdentityOrchestration/TSIdoGenerateDebugPinCompletion":{"kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration\/TSIdoGenerateDebugPinCompletion","title":"TSIdoGenerateDebugPinCompletion","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"TSIdoGenerateDebugPinCompletion","kind":"identifier"}],"type":"topic","url":"\/documentation\/identityorchestration\/tsidogeneratedebugpincompletion","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TSIdoGenerateDebugPinCompletion"}]},"doc://com.TransmitSecurity.IdentityOrchestration/documentation/IdentityOrchestration/TSIdoDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TSIdoDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"TSIdoDelegate","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The delegate that will be called when the IdoServiceResponse is received."}],"title":"TSIdoDelegate","url":"\/documentation\/identityorchestration\/tsidodelegate","type":"topic","identifier":"doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration\/TSIdoDelegate","role":"symbol"},"doc://com.TransmitSecurity.IdentityOrchestration/documentation/IdentityOrchestration/TSIdoStartJourneyOptions":{"url":"\/documentation\/identityorchestration\/tsidostartjourneyoptions","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSIdoStartJourneyOptions"}],"navigatorTitle":[{"text":"TSIdoStartJourneyOptions","kind":"identifier"}],"identifier":"doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration\/TSIdoStartJourneyOptions","abstract":[{"type":"text","text":"Additional parameters to be passed to the journey."}],"role":"symbol","title":"TSIdoStartJourneyOptions","kind":"symbol"},"doc://com.TransmitSecurity.IdentityOrchestration/documentation/IdentityOrchestration/IdentityOrchestrationVersionNumber":{"url":"\/documentation\/identityorchestration\/identityorchestrationversionnumber","identifier":"doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration\/IdentityOrchestrationVersionNumber","title":"IdentityOrchestrationVersionNumber","type":"topic","role":"symbol","fragments":[{"text":"IdentityOrchestrationVersionNumber","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Project version number for IdentityOrchestration."}]},"doc://com.TransmitSecurity.IdentityOrchestration/documentation/IdentityOrchestration/TSIdoClientResponseOption":{"url":"\/documentation\/identityorchestration\/tsidoclientresponseoption","type":"topic","abstract":[{"type":"text","text":"The interface for client response option object. Use this object to submit client input to the Journey step to process, cancel the current step or choose a custom branch."}],"navigatorTitle":[{"text":"TSIdoClientResponseOption","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TSIdoClientResponseOption"}],"identifier":"doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration\/TSIdoClientResponseOption","kind":"symbol","title":"TSIdoClientResponseOption","role":"symbol"},"doc://com.TransmitSecurity.IdentityOrchestration/documentation/IdentityOrchestration/TSIdoServiceResponse":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"TSIdoServiceResponse","kind":"identifier"}],"identifier":"doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration\/TSIdoServiceResponse","navigatorTitle":[{"text":"TSIdoServiceResponse","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/identityorchestration\/tsidoserviceresponse","title":"TSIdoServiceResponse","type":"topic","abstract":[{"type":"text","text":"The interface for the Journey step response object. Including Journey end with either error, rejection and success."}]},"doc://com.TransmitSecurity.IdentityOrchestration/documentation/IdentityOrchestration":{"url":"\/documentation\/identityorchestration","type":"topic","identifier":"doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration","kind":"symbol","abstract":[],"title":"IdentityOrchestration","role":"collection"},"doc://com.TransmitSecurity.IdentityOrchestration/documentation/IdentityOrchestration/TSIdoJourneyActionType":{"url":"\/documentation\/identityorchestration\/tsidojourneyactiontype","role":"symbol","title":"TSIdoJourneyActionType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSIdoJourneyActionType"}],"identifier":"doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration\/TSIdoJourneyActionType","abstract":[{"type":"text","text":"The enum for the Journey step ID, when the journey step is a known action and not a custom form."}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TSIdoJourneyActionType"}]},"doc://com.TransmitSecurity.IdentityOrchestration/documentation/IdentityOrchestration/TSIdoInitJourneyOptions":{"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TSIdoInitJourneyOptions"}],"title":"TSIdoInitJourneyOptions","url":"\/documentation\/identityorchestration\/tsidoinitjourneyoptions","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TSIdoInitJourneyOptions"}],"identifier":"doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration\/TSIdoInitJourneyOptions","kind":"symbol","abstract":[{"type":"text","text":"Additional environment configuration for the SDK operation."}]},"doc://com.TransmitSecurity.IdentityOrchestration/documentation/IdentityOrchestration/TSIdoClientResponseOptionType":{"title":"TSIdoClientResponseOptionType","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TSIdoClientResponseOptionType"}],"kind":"symbol","navigatorTitle":[{"text":"TSIdoClientResponseOptionType","kind":"identifier"}],"identifier":"doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration\/TSIdoClientResponseOptionType","abstract":[{"text":"The enum for the client response option types.","type":"text"}],"url":"\/documentation\/identityorchestration\/tsidoclientresponseoptiontype","role":"symbol"},"doc://com.TransmitSecurity.IdentityOrchestration/documentation/IdentityOrchestration/IdentityOrchestrationVersionString":{"role":"symbol","title":"IdentityOrchestrationVersionString","abstract":[{"type":"text","text":"Project version string for IdentityOrchestration."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration\/IdentityOrchestrationVersionString","fragments":[{"text":"IdentityOrchestrationVersionString","kind":"identifier"}],"url":"\/documentation\/identityorchestration\/identityorchestrationversionstring"},"doc://com.TransmitSecurity.IdentityOrchestration/documentation/IdentityOrchestration/TSIdoSdkError":{"type":"topic","abstract":[{"text":"The common struct for Promise rejections. Developers should handle according to the ‘errorCode’","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TSIdoSdkError","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration\/TSIdoSdkError","url":"\/documentation\/identityorchestration\/tsidosdkerror","title":"TSIdoSdkError","role":"symbol","navigatorTitle":[{"text":"TSIdoSdkError","kind":"identifier"}]},"doc://com.TransmitSecurity.IdentityOrchestration/documentation/IdentityOrchestration/Swift":{"abstract":[],"url":"\/documentation\/identityorchestration\/swift","identifier":"doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration\/Swift","role":"collection","title":"Swift","type":"topic","kind":"symbol"},"doc://com.TransmitSecurity.IdentityOrchestration/documentation/IdentityOrchestration/TSIdoJourneyError":{"abstract":[{"text":"The enum for the start Journey errors.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"TSIdoJourneyError"}],"title":"TSIdoJourneyError","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"TSIdoJourneyError","kind":"identifier"}],"identifier":"doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration\/TSIdoJourneyError","url":"\/documentation\/identityorchestration\/tsidojourneyerror"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration\/IdentityOrchestrationVersionNumber","doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration\/IdentityOrchestrationVersionString"],"title":"Variables"}]},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"}],"traits":[{"interfaceLanguage":"occ"}]}]}